const mongoose = require('mongoose');

const plantsSchema = new mongoose.Schema({
    id: String,
    scientific_name: String,
    rank: String,
    genus: String,
    family: String,
    year: String,
    author: String,
    bibliography: String,
    common_name: String,
    family_common_name: String,
    image_url: String,
    flower_color: String,
    flower_conspicuous: String,
    foliage_color: String,
    foliage_texture: String,
    fruit_color: String,
    fruit_conspicuous: String,
    fruit_months: String,
    bloom_months: String,
    ground_humidity: String,
    growth_form: String,
    growth_habit: String,
    growth_months: String,
    growth_rate: String,
    edible_part: String,
    vegetable: String,
    edible: String,
    light: String,
    soil_nutriments: String,
    soil_salinity: String,
    anaerobic_tolerance: String,
    atmospheric_humidity: String,
    average_height_cm: String,
    maximum_height_cm: String,
    minimum_root_depth_cm: String,
    ph_maximum: String,
    ph_minimum: String,
    planting_days_to_harvest: String,
    planting_description: String,
    planting_sowing_description: String,
    planting_row_spacing_cm: String,
    planting_spread_cm: String,
    synonyms: String,
    distributions: String,
    common_names: String,
    url_usda: String,
    url_tropicos: String,
    url_tela_botanica: String,
    url_powo: String,
    url_plantnet: String,
    url_gbif: String,
    url_openfarm: String,
    url_catminat: String,
    url_wikipedia_en: String
});

const Plants = mongoose.model('Plants', plantsSchema, 'Plants');

module.exports = Plants;